development:
  secret_key_base: 524bfc83ece75c2f15efae497f9d868794d72fbc2f55412a7db8dcd4305f6ca8a2fffbb132fb9a212cccc3d5100f8d87d93489b0ba4d960338ec14cc5f45262a
  api_host: <%= ENV["API_HOST"].presence || "http://sketches.quintype.com" %>
  asset_host: "http://localhost:3000"
  title: "Coconut"
  integrations:
    chartbeat:
      uid: "NOT_A_VALID_ID"
      domain: "NOT_A_VALID_DOMAIN"

test:
  secret_key_base: 79fb63426d0e66d2a681978727f4e9c3caa6bf747354d1b14fbba315132311c92fbdc5b752df8778294958c2cbf876cb4a89caad87ff2c9899e6405b41600dde
  api_host: <%= ENV["API_HOST"].presence || "http://localhost:8001" %>
  cdn_image: <%= ENV["CDN_IMAGE"].presence || "qt-staging-01.imgix.net" %>
  asset_host: "http://localhost:3000"
  title: "Coconut"
  integrations:
    chartbeat:
      uid: "NOT_A_VALID_ID"
      domain: "NOT_A_VALID_DOMAIN"

production:
  secret_key_base: 524bfc83ece75c2f15efae497f9d868794d72fbc2f55412a7db8dcd4305f6ca8a2fffbb132fb9a212cccc3d5100f8d87d93489b0ba4d960338ec14cc5f45262a
  api_host: <%= ENV["API_HOST"].presence || "http://localhost:8001" %>
  cdn_image: <%= ENV["CDN_IMAGE"].presence || "qt-staging-01.imgix.net" %>
  asset_host: "http://localhost:3000"
  title: "Coconut"
  integrations:
    chartbeat:
      uid: "NOT_A_VALID_ID"
      domain: "NOT_A_VALID_DOMAIN"
