# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 524bfc83ece75c2f15efae497f9d868794d72fbc2f55412a7db8dcd4305f6ca8a2fffbb132fb9a212cccc3d5100f8d87d93489b0ba4d960338ec14cc5f45262a

test:
  secret_key_base: 79fb63426d0e66d2a681978727f4e9c3caa6bf747354d1b14fbba315132311c92fbdc5b752df8778294958c2cbf876cb4a89caad87ff2c9899e6405b41600dde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
